### ISSUE TITLE
Exception on a long-time connection (???)

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-query-engine#151]
It seems that it is only possible to attach  image files (.jpeg, .png etc) here in this board... So I renamed files... but their names are:
building_blocks.py
go-namespace.json
fb_das_queries_ontos_tmp.py

Please, send me an email (saulo@singularitynet.io) or message in MatterMost (@saulo) that I'll send them...

Consistently, an exception has been raised (listed below) when running this attached code since Thursday when I finished writing it. Coincidentally, my internet connection has been unstable since Thursday. So, I don't know if that's the issue, and I need someone in another region to run the code to see if the behavior is the same. Just put the three files in the same directory and run "fb_das_queries_ontos_tmp.py". The method takes time: build_ontologies_nets()

Here at home (Belo Horizonte, Brazil), it has been running for a while and stops for minutes at a point like this:

Typed network for gene msl-1:
2024-02-24 10:48:58.803225

Then, it raises an exception (requests.exceptions.JSONDecodeError) with different "causes." For example, these three most recent ones:

requests.exceptions.JSONDecodeError: Expecting ',' delimiter: line 16655 column 2 (char 588527)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 21226 column 19 (char 746432)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 18011 column 18 (char 634112)

When running, the exception takes minutes (8, 10, or more) to be listed after a message like this:

Typed network for gene Su(var)205:
2024-02-24 11:12:03.875969

In fact, I've a record when the processing stopped for about 7 minutes and was resumed and finished successfully. But at time of this writing, i attached a screenshot in which the code is stopped since yesterday:

Typed network for gene Rbf:
2024-02-25 22:02:21.757340

Here's a complete list for a crashed run:

(base) saulo@logos:~/snet/hyperon/github/das-2024-02-02/flybase2metta/queries$ python fb_das_queries_ontos_tmp.py 
Connected to DAS at 104.238.183.115:8081

Typed network for gene Su(var)205:
2024-02-24 10:48:35.199443
2024-02-24 10:48:58.802870
Retrieval elapsed time: 23.603426694869995
Net type: CellularComponent
Number of terms: 14
('CellularComponent', 'heterochromatin', 'GO:0000792')
('CellularComponent', 'polytene chromosome', 'GO:0005700')
('CellularComponent', 'polytene chromosome puff', 'GO:0005703')
('CellularComponent', 'chromocenter', 'GO:0010369')
('CellularComponent', 'chromosome, centromeric region', 'GO:0000775')
('CellularComponent', 'polytene chromosome interband', 'GO:0005705')
('CellularComponent', 'euchromatin', 'GO:0000791')
('CellularComponent', 'pericentric heterochromatin', 'GO:0005721')
('CellularComponent', 'condensed chromosome', 'GO:0000793')
('CellularComponent', 'chromosome, telomeric region', 'GO:0000781')
('CellularComponent', 'nucleus', 'GO:0005634')
('CellularComponent', 'polytene chromosome chromocenter', 'GO:0005701')
('CellularComponent', 'chromosome', 'GO:0005694')
('CellularComponent', 'condensed chromosome, centromeric region', 'GO:0000779')

Typed network for gene msl-1:
2024-02-24 10:48:58.803225
Traceback (most recent call last):
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/saulo/anaconda3/lib/python3.9/json/init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/saulo/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/saulo/anaconda3/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 18011 column 18 (char 634112)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saulo/snet/hyperon/github/das-2024-02-02/flybase2metta/queries/fb_das_queries_ontos_tmp.py", line 169, in <module>
    test()
  File "/home/saulo/snet/hyperon/github/das-2024-02-02/flybase2metta/queries/fb_das_queries_ontos_tmp.py", line 166, in test
    build_ontologies_nets(net_act_list, net_node_type, querier)
  File "/home/saulo/snet/hyperon/github/das-2024-02-02/flybase2metta/queries/fb_das_queries_ontos_tmp.py", line 101, in build_ontologies_nets
    net = querier.gene_centered_net(gene_symbol, net_node_type)
  File "/home/saulo/snet/hyperon/github/das-2024-02-02/flybase2metta/queries/fb_das_queries_ontos_tmp.py", line 50, in gene_centered_net
    query_answer = self.das.query({
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/hyperon_das/das.py", line 308, in query
    return self.query_engine.query(query, parameters)
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/hyperon_das/query_engines.py", line 340, in query
    answer = self.remote_das.query(query, parameters)
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/hyperon_das/client.py", line 80, in query
    return self._send_request(payload)
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/hyperon_das/client.py", line 24, in _send_request
    raise e
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/hyperon_das/client.py", line 20, in _send_request
    return response.json()
  File "/home/saulo/anaconda3/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 18011 column 18 (char 634112)

![Image](https://github.com/singnet/das-query-engine/assets/40299005/6f4b3e64-6455-44ce-9646-2e8c36585abc)
![Image](https://github.com/singnet/das-query-engine/assets/40299005/676a8a44-9a1a-4d40-b4ac-db2164c48afb)
![Image](https://github.com/singnet/das-query-engine/assets/40299005/26cc9ee2-d248-491b-86d4-487b4c8ba07c)

![Image](https://github.com/singnet/das-query-engine/assets/40299005/310303e0-c050-4f9a-a696-49762ad716ad)

**Comment by marcocapozzoli** [comment]
Issue closed because it was not productive
